// <auto-generated />
namespace MakePizza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddUP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUP));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181415151_AddUP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
